# Generated by Django 5.2.1 on 2025-05-08 20:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='media/no-portada.svg', upload_to='books/', verbose_name='Portada'),
        ),
        migrations.AlterField(
            model_name='book',
            name='sinopsis',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Sinopsis'),
        ),
    ]
