# Generated by Django 5.2.1 on 2025-05-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_image_alter_book_sinopsis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='books/', verbose_name='Portada'),
        ),
        migrations.AlterField(
            model_name='book',
            name='sinopsis',
            field=models.TextField(blank=True, null=True, verbose_name='Sinopsis'),
        ),
    ]
