# Generated by Django 5.2.1 on 2025-05-11 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_genre_alter_book_image_book_generes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='generes',
            new_name='genres',
        ),
    ]
