# Generated by Django 5.2.1 on 2025-05-11 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_rename_generes_book_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(blank=True, null=True, related_name='get_books', to='books.genre', verbose_name='Género'),
        ),
    ]
