# Generated by Django 5.2.1 on 2025-05-12 12:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_genre_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='owned',
            field=models.ManyToManyField(related_name='maps', to=settings.AUTH_USER_MODEL, verbose_name='Pertenece'),
        ),
    ]
